export const strings = {
  home: {
    greeting: 'Good evening',
    brand: 'MovieFlix',
    subtitle: 'Find movies, shows, and original stories.',
    premium: 'Premium',
    featured: 'Featured',
    loading: 'Loading your next watch…',
    categories: 'Categories',
    topIn: 'Top 10 in',
    more: 'More',
    noFeatured: 'No featured movie available',
    noMoviesFound: 'No movies found',
    seeAll: 'See all',
    continueWatching: 'Continue Watching',
    keepWatching: 'Keep watching',
    completeSuffix: 'complete',
    moviesSuffix: 'Movies',
  },
  search: {
    title: 'Search',
    subtitle: 'Find titles, genres, or actors.',
    placeholder: 'Search movies...',
    results: 'Results',
    topPicks: 'Top Picks',
    found: 'found',
    noResults: 'No movies match your search.',
  },
  sections: {
    trending: 'Trending',
    popular: 'Popular',
    action: 'Action',
    comedy: 'Comedy',
  },
  details: {
    storyline: 'Storyline',
    moreLikeThis: 'More Like This',
    director: 'Director',
    cast: 'Cast',
    back: 'Back',
    runtime: 'Runtime',
  },
  categoryList: {
    allMovies: 'All Movies',
    movies: 'Movies',
    loading: 'Loading movies…',
    empty: 'No movies found for this category.',
  },
  emptyState: {
    title: 'No Movies Found',
    subtitle: 'Try refreshing the page or adjusting your search filters.',
    cta: 'Browse Again',
  },
  errorState: {
    title: 'Something Went Wrong',
    subtitle: "We couldn't load the movies right now. Please check your connection and try again.",
    cta: 'Retry',
  },
  loading: {
    title: 'Loading your movies...',
  },
  profile: {
    title: 'Profile',
    name: 'User',
    username: '@moviefan_27',
    profileImageUrl: 'https://i.pravatar.cc/300?img=12',
    signedOutUser: 'Guest User',
    subtitle: 'Manage your preferences and account settings.',
    accountDetails: 'Account Details',
    email: 'karan@example.com',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    privacy: 'Privacy',
    logout: 'Logout',
    settings: 'Settings',
    enabled: 'Enabled',
    disabled: 'Disabled',
    on: 'On',
    off: 'Off',
    viewPolicy: 'View Policy',
    privacyUrl: 'https://www.example.com/privacy',
    privacyError: 'Unable to open the privacy policy right now. Please try again later.',
    notificationsEnabledMsg: 'Notifications are now enabled.',
    notificationsDisabledMsg: 'Notifications are now disabled.',
    cancel: 'Cancel',
    confirmLogout: 'Log out',
    logoutConfirmMessage: 'Are you sure you want to log out from this account?',
    loggingOut: 'Logging out...',
    signedOut: 'Signed out',
    logoutSuccess: 'You have been logged out successfully.',
  },
};
